services:
  standalone:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: ${INSTANCE_NAME:-my-xte-scenario}-standalone
    environment:
      ENVIRONMENT: standalone
      INSTANCE_NAME: ${INSTANCE_NAME:-my-xte-scenario}
      TEI_FILE: ${TEI_FILE:-**/*.xml}
      ANT_BUILDFILE: ${ANT_BUILDFILE:-bin/build.xml}
      XSLT_ENTRYPOINT: ${XSLT_ENTRYPOINT:-xslt/TEI-to-HTML.xsl}
      OUTPUT_EXTENSION: ${OUTPUT_EXTENSION:-html}
      EXPAND_DEFAULT_ATTRIBUTES: ${EXPAND_DEFAULT_ATTRIBUTES:-false}
      ANT_TARGET: ${ANT_TARGET:-full}
      ALLOW_DELETE: false
    volumes:
      - out:/tmp/opt/cdcp/out
      - source:/tmp/opt/cdcp/source
    entrypoint: [ "bash", "-c", "-l", "/var/task/standalone.sh" ]
volumes:
  out:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./out
  source:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./source
